name: Build Electron App

on:
  push:
    tags:
      - "v*"

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run dist

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: sudo apt-get update
      - run: sudo apt-get install -y dpkg fakeroot

      - run: npm install

      - run: npm run dist

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/